package com.example.agent.browser

/**
 * JavaScript builders and result decoding for [WebViewBrowserEngine].
 *
 * Everything in here is deliberately free of Android imports: the engine only calls
 * `WebView.evaluateJavascript`, while *what* is executed and *how the answer is read* lives here
 * so it can be unit-tested on a plain JVM (see `BrowserScriptsTest`).
 *
 * **Result encoding.** Android serialises the value returned by `evaluateJavascript` as JSON, so
 * a script that returns the JavaScript string `'ok'` arrives at the callback as `"ok"` — with the
 * surrounding double quotes. Reading actions therefore go through [stripQuotes]; every action
 * script returns a short, quote-free token (`ok`, `not-found`, `occluded …`) so one unquote step
 * is enough. The page snapshot is an object, which serialises as a JSON object and is parsed
 * directly.
 *
 * **Injection safety.** Ref values are re-validated by [safeRef] inside every builder, and dynamic
 * values only ever reach the page through [jsStringLiteral]. A ref that fails validation produces
 * [INVALID_REF_SCRIPT], which returns a token instead of embedding anything into the script.
 */
internal object BrowserScripts {

    /** Refs are generated by the snapshot script (`agx-0`, `agx-1`, …); anything else is rejected. */
    private val REF_PATTERN = Regex("^[a-z0-9\\-]{1,24}$")

    /** Returned instead of a real script when the ref cannot be trusted. */
    private const val INVALID_REF_SCRIPT = "(function(){ return 'invalid-ref'; })()"

    /**
     * Normalises and validates a ref. Returns `null` when it cannot be used, in which case the
     * caller must report the error instead of running a script.
     */
    fun safeRef(ref: String): String? {
        val trimmed = ref.trim().lowercase()
        return if (REF_PATTERN.matches(trimmed)) trimmed else null
    }

    /**
     * Encodes [value] as a JavaScript string literal. Hand-rolled (instead of `org.json`, which is
     * only a stub in plain JVM tests) and safe against quote/backslash/newline injection.
     */
    fun jsStringLiteral(value: String): String = buildString(value.length + 2) {
        append('"')
        for (ch in value) {
            when (ch) {
                '"' -> append("\\\"")
                '\\' -> append("\\\\")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                '\u0008' -> append("\\b")
                '\u000C' -> append("\\f")
                '\u2028' -> append("\\u2028")
                '\u2029' -> append("\\u2029")
                else -> if (ch < ' ') {
                    append("\\u")
                    append(ch.code.toString(16).padStart(4, '0'))
                } else {
                    append(ch)
                }
            }
        }
        append('"')
    }

    /**
     * Undoes the JSON string encoding applied by `evaluateJavascript`.
     *
     * `"ok"` → `ok`, `ok` → `ok` (some WebView builds hand back the raw value), `null` → `null`,
     * and a Kotlin `null` stays `null`. Escape sequences are decoded so a payload containing a
     * quote survives the round-trip.
     */
    fun stripQuotes(raw: String?): String? {
        if (raw == null) return null
        val trimmed = raw.trim()
        if (trimmed == "null") return null
        if (trimmed.length < 2 || !trimmed.startsWith("\"") || !trimmed.endsWith("\"")) return trimmed
        val inner = trimmed.substring(1, trimmed.length - 1)
        val out = StringBuilder(inner.length)
        var i = 0
        while (i < inner.length) {
            val ch = inner[i]
            if (ch != '\\' || i == inner.length - 1) {
                out.append(ch)
                i++
                continue
            }
            when (val next = inner[i + 1]) {
                '"' -> { out.append('"'); i += 2 }
                '\\' -> { out.append('\\'); i += 2 }
                '/' -> { out.append('/'); i += 2 }
                'n' -> { out.append('\n'); i += 2 }
                'r' -> { out.append('\r'); i += 2 }
                't' -> { out.append('\t'); i += 2 }
                'b' -> { out.append('\b'); i += 2 }
                'f' -> { out.append('\u000C'); i += 2 }
                'u' -> {
                    val hex = inner.substring(i + 2, minOf(i + 6, inner.length))
                    val code = if (hex.length == 4) hex.toIntOrNull(16) else null
                    if (code != null) {
                        out.append(code.toChar())
                        i += 6
                    } else {
                        out.append(next)
                        i += 2
                    }
                }
                else -> { out.append(next); i += 2 }
            }
        }
        return out.toString()
    }

    /** True when the two fingerprints differ; an unavailable fingerprint never claims "no change". */
    fun changedBetween(before: String, after: String): Boolean {
        if (before.isEmpty() || after.isEmpty()) return true
        return before != after
    }

    /**
     * Turns a page-level failure token into an instruction the model can act on. Kept here (and
     * not inline in the engine) so the wording is testable.
     */
    fun describeToken(token: String, ref: String): String {
        val target = if (ref.isBlank()) "Elemen target" else "Elemen $ref"
        return when {
            token == "not-found" ->
                "$target sudah tidak ada di halaman (DOM berubah setelah aksi sebelumnya). " +
                    "Ambil snapshot baru dengan browser_read, lalu ulangi memakai ref yang baru."

            token == "disabled" -> "$target sedang nonaktif (disabled) di halaman."
            token == "readonly" -> "$target hanya-baca (readonly), jadi tidak bisa diisi."
            token == "invisible" -> "$target tidak terlihat (ukuran nol), jadi tidak bisa diaksi."
            token == "invalid-ref" -> "Ref elemen tidak valid: \"$ref\". Pakai ref dari browser_read."
            token.startsWith("occluded") ->
                "$target tertutup elemen lain di halaman ($token). Tutup overlay/modal lebih dulu " +
                    "(mis. browser_press_key Escape), ambil browser_read, lalu ulangi."

            token == "not-a-select" -> "$target bukan elemen <select>, jadi browser_select tidak berlaku."
            token == "option-not-found" -> "Opsi yang diminta tidak ada di <select> $target."
            token == "unsupported-key" ->
                "Tombol itu belum didukung. Pakai Enter, Escape, Tab, Backspace, Space, " +
                    "ArrowUp, ArrowDown, ArrowLeft, atau ArrowRight."

            token.startsWith("error") -> "Aksi gagal di halaman: $token"
            token.isBlank() -> "Aksi gagal di halaman (tidak ada jawaban dari halaman)."
            else -> "Aksi gagal di halaman ($token)."
        }
    }

    // ------------------------------------------------------------------------------------------
    // Keyboard
    // ------------------------------------------------------------------------------------------

    private val KEY_ALIASES: Map<String, String> = mapOf(
        "enter" to "Enter", "return" to "Enter",
        "esc" to "Escape", "escape" to "Escape",
        "tab" to "Tab",
        "backspace" to "Backspace", "back" to "Backspace",
        "space" to "Space", "spasi" to "Space",
        "arrowup" to "ArrowUp", "up" to "ArrowUp", "atas" to "ArrowUp",
        "arrowdown" to "ArrowDown", "down" to "ArrowDown", "bawah" to "ArrowDown",
        "arrowleft" to "ArrowLeft", "left" to "ArrowLeft", "kiri" to "ArrowLeft",
        "arrowright" to "ArrowRight", "right" to "ArrowRight", "kanan" to "ArrowRight"
    )

    /** Keys that can be sent with [pressKey]; also the vocabulary the tool advertises. */
    val SUPPORTED_KEYS: Set<String> = KEY_ALIASES.values.toSet()

    /** Accepts `Enter`, `enter`, `esc`, `bawah`, … and returns the canonical key name, or null. */
    fun normalizeKey(key: String): String? = KEY_ALIASES[key.trim().lowercase()]

    // ------------------------------------------------------------------------------------------
    // Element identity fallback
    // ------------------------------------------------------------------------------------------

    /**
     * Finds the element that most likely *is* [remembered] after the page re-rendered and the
     * original ref went stale. Matching is intentionally honest: an exact tag/type/label match
     * first, then an exact value match, then a label-only match — never a positional guess.
     */
    fun matchDescriptor(remembered: BrowserElement?, candidates: List<BrowserElement>): String? {
        if (remembered == null) return null
        if (remembered.label.isNotBlank()) {
            candidates.firstOrNull {
                it.tag == remembered.tag && it.type == remembered.type &&
                    it.label.equals(remembered.label, ignoreCase = true)
            }?.let { return it.ref }
        }
        if (remembered.value.isNotBlank()) {
            candidates.firstOrNull {
                it.tag == remembered.tag && it.type == remembered.type &&
                    it.value == remembered.value
            }?.let { return it.ref }
        }
        if (remembered.label.isNotBlank()) {
            candidates.firstOrNull {
                it.tag == remembered.tag && it.label.equals(remembered.label, ignoreCase = true)
            }?.let { return it.ref }
        }
        return null
    }

    // ------------------------------------------------------------------------------------------
    // Observation
    // ------------------------------------------------------------------------------------------

    /**
     * Compact page fingerprint: URL, title, node count, visible-text length, a hash of every form
     * field value, open dialogs and scroll offset. Two samples that are equal mean "nothing
     * observable happened"; different samples mean the action did something. Field values are
     * included so typing into an input is detected even though the text and node count do not
     * change.
     */
    val FINGERPRINT: String = """
        (function(){
          try {
            var body = document.body;
            var text = body ? (body.innerText || '') : '';
            var fields = document.querySelectorAll('input,textarea,select');
            var acc = 0;
            for (var i = 0; i < fields.length; i++) {
              var v = String(fields[i].value == null ? '' : fields[i].value);
              var c = v.length > 0 ? v.charCodeAt(0) : 0;
              acc = (acc * 31 + v.length + c * (i + 1)) % 2147483647;
            }
            var dialogs = document.querySelectorAll('[role=dialog],dialog[open],[aria-modal=true]').length;
            var scroll = Math.round(window.scrollY || 0);
            return [
              location.href,
              document.title || '',
              document.querySelectorAll('*').length,
              text.length,
              acc,
              dialogs,
              scroll
            ].join('|');
          } catch (e) {
            return 'err';
          }
        })()
    """.trimIndent()

    /**
     * Resets a mutation counter and makes sure a `MutationObserver` is watching the document. A
     * counter (instead of a diff) keeps the settle loop cheap: one small string per poll.
     */
    val ARM_SETTLE: String = """
        (function(){
          try {
            window.__agx = window.__agx || { n: 0 };
            window.__agx.n = 0;
            if (!window.__agxObserver) {
              window.__agxObserver = new MutationObserver(function(){ window.__agx.n++; });
            }
            window.__agxObserver.observe(document.documentElement || document, {
              subtree: true, childList: true, attributes: true, characterData: true
            });
            return 'ok';
          } catch (e) {
            return 'ok';
          }
        })()
    """.trimIndent()

    /** One cheap settle sample: document readiness plus the number of DOM mutations so far. */
    val SETTLE_SAMPLE: String = """
        (function(){
          try {
            var a = window.__agx || { n: 0 };
            return document.readyState + '|' + a.n;
          } catch (e) {
            return 'unknown|0';
          }
        })()
    """.trimIndent()

    /**
     * The page snapshot: readable text plus every interactive element, each tagged with
     * `data-agx-ref` so later calls can address it. The selector covers native controls, the ARIA
     * roles real sites use, and custom widgets built from divs.
     */
    val SNAPSHOT: String = """
        (function(){
          try {
            var selector = 'a,button,input,textarea,select,summary,' +
              '[role=button],[role=link],[role=menuitem],[role=menuitemcheckbox],[role=tab],' +
              '[role=checkbox],[role=radio],[role=switch],[role=combobox],[role=option],' +
              '[role=searchbox],[role=textbox],[contenteditable=""],[contenteditable=true],' +
              '[tabindex]:not([tabindex="-1"])';
            var nodes = document.querySelectorAll(selector);
            var out = [];
            var i = 0;
            for (var k = 0; k < nodes.length && i < 80; k++) {
              var el = nodes[k];
              var r = el.getBoundingClientRect();
              if (r.width <= 0 || r.height <= 0) continue;
              var ref = 'agx-' + i;
              try { el.setAttribute('data-agx-ref', ref); } catch (e) {}
              var label = el.getAttribute('aria-label') ||
                el.getAttribute('title') ||
                el.getAttribute('alt') ||
                el.getAttribute('data-testid') ||
                el.getAttribute('placeholder') ||
                (el.innerText || el.textContent) ||
                el.value ||
                el.name ||
                el.id ||
                '';
              out.push({
                ref: ref,
                tag: (el.tagName || '').toLowerCase(),
                type: (el.getAttribute('type') || ''),
                label: ('' + label).replace(/\s+/g, ' ').trim().slice(0, 90),
                value: ('' + (el.value || '')).slice(0, 90)
              });
              i++;
            }
            return {
              url: location.href,
              title: document.title || '',
              text: (document.body ? (document.body.innerText || '') : '').slice(0, 20000),
              elements: out
            };
          } catch (e) {
            return { url: location.href, title: '', text: '', elements: [], error: '' + e };
          }
        })()
    """.trimIndent()

    // ------------------------------------------------------------------------------------------
    // Actions
    // ------------------------------------------------------------------------------------------

    /**
     * Clicks an element, but only after checking that it is still the thing on screen: present,
     * sized, enabled, and actually the topmost element at its own centre. That last check is what
     * stops a programmatic `click()` from firing a control that a modal or overlay has covered.
     */
    fun click(ref: String): String {
        val safe = safeRef(ref) ?: return INVALID_REF_SCRIPT
        return """
            (function(){
              try {
                var el = document.querySelector('[data-agx-ref="$safe"]');
                if (!el) return 'not-found';
                var r = el.getBoundingClientRect();
                if (r.width <= 0 || r.height <= 0) return 'invisible';
                if (el.disabled === true || el.getAttribute('aria-disabled') === 'true') return 'disabled';
                try { el.scrollIntoView({ block: 'center' }); } catch (e) {}
                var rr = el.getBoundingClientRect();
                var cx = Math.min(Math.max(rr.left + rr.width / 2, 1), Math.max(window.innerWidth - 1, 1));
                var cy = Math.min(Math.max(rr.top + rr.height / 2, 1), Math.max(window.innerHeight - 1, 1));
                var top = document.elementFromPoint(cx, cy);
                if (top && top !== el && !el.contains(top) && !top.contains(el)) {
                  var by = (top.tagName || '') + ' ' + (top.getAttribute('aria-label') || top.innerText || '');
                  return 'occluded ' + String(by).replace(/["\\\n\r]/g, ' ').trim().slice(0, 40);
                }
                try { el.focus(); } catch (e) {}
                el.click();
                return 'ok';
              } catch (e) {
                return 'error ' + String(e).replace(/["\\\n\r]/g, ' ').slice(0, 120);
              }
            })()
        """.trimIndent()
    }

    /**
     * Types [literal] (an already-encoded JS string literal) into an element.
     *
     * Text inputs are filled through the *prototype* value setter, because frameworks like React
     * and Vue keep their own value tracker and ignore a plain `el.value = …` assignment — that is
     * the classic "the form looks filled but submits empty" failure. `<select>` is handled by
     * matching the requested value against the options, `contenteditable` through `insertText`.
     */
    fun type(ref: String, literal: String, submit: Boolean): String {
        val safe = safeRef(ref) ?: return INVALID_REF_SCRIPT
        val submitLiteral = if (submit) "true" else "false"
        return """
            (function(){
              try {
                var el = document.querySelector('[data-agx-ref="$safe"]');
                if (!el) return 'not-found';
                if (el.disabled === true) return 'disabled';
                if (el.readOnly === true) return 'readonly';
                var r = el.getBoundingClientRect();
                if (r.width <= 0 || r.height <= 0) return 'invisible';
                try { el.scrollIntoView({ block: 'center' }); } catch (e) {}
                try { el.focus(); } catch (e) {}
                var value = $literal;
                if (el.isContentEditable) {
                  var inserted = false;
                  try { inserted = document.execCommand('insertText', false, value); } catch (e) { inserted = false; }
                  if (!inserted) { el.innerText = value; }
                  el.dispatchEvent(new Event('input', { bubbles: true }));
                  el.dispatchEvent(new Event('change', { bubbles: true }));
                } else if (el.tagName === 'SELECT') {
                  var matched = null;
                  var opts = el.options || [];
                  for (var i = 0; i < opts.length; i++) {
                    if (String(opts[i].value) === value) { matched = opts[i]; break; }
                  }
                  if (!matched) {
                    for (var j = 0; j < opts.length; j++) {
                      var exact = String(opts[j].text || '').trim().toLowerCase();
                      if (exact === value.toLowerCase()) { matched = opts[j]; break; }
                    }
                  }
                  if (!matched) {
                    for (var k = 0; k < opts.length; k++) {
                      var loose = String(opts[k].text || '').trim().toLowerCase();
                      if (loose.indexOf(value.toLowerCase()) !== -1) { matched = opts[k]; break; }
                    }
                  }
                  if (!matched) return 'option-not-found';
                  el.value = matched.value;
                  el.dispatchEvent(new Event('input', { bubbles: true }));
                  el.dispatchEvent(new Event('change', { bubbles: true }));
                } else {
                  var proto = (el.tagName === 'TEXTAREA')
                    ? window.HTMLTextAreaElement.prototype
                    : window.HTMLInputElement.prototype;
                  var desc = Object.getOwnPropertyDescriptor(proto, 'value');
                  if (desc && desc.set) { desc.set.call(el, value); } else { el.value = value; }
                  el.dispatchEvent(new Event('input', { bubbles: true }));
                  el.dispatchEvent(new Event('change', { bubbles: true }));
                }
                if ($submitLiteral) {
                  var form = el.form;
                  if (form) {
                    if (typeof form.requestSubmit === 'function') {
                      try { form.requestSubmit(); } catch (e) { form.submit(); }
                    } else {
                      form.submit();
                    }
                  } else {
                    var opts2 = { key: 'Enter', code: 'Enter', keyCode: 13, which: 13, bubbles: true };
                    el.dispatchEvent(new KeyboardEvent('keydown', opts2));
                    el.dispatchEvent(new KeyboardEvent('keyup', opts2));
                  }
                }
                return 'ok';
              } catch (e) {
                return 'error ' + String(e).replace(/["\\\n\r]/g, ' ').slice(0, 120);
              }
            })()
        """.trimIndent()
    }

    /** Chooses an option in a native `<select>` by value, exact label, then partial label. */
    fun select(ref: String, literal: String): String {
        val safe = safeRef(ref) ?: return INVALID_REF_SCRIPT
        return """
            (function(){
              try {
                var el = document.querySelector('[data-agx-ref="$safe"]');
                if (!el) return 'not-found';
                if (el.tagName !== 'SELECT') return 'not-a-select';
                if (el.disabled === true) return 'disabled';
                var want = $literal;
                var opts = el.options || [];
                var target = null;
                for (var i = 0; i < opts.length; i++) {
                  if (String(opts[i].value) === want) { target = opts[i]; break; }
                }
                if (!target) {
                  for (var j = 0; j < opts.length; j++) {
                    var exact = String(opts[j].text || '').trim().toLowerCase();
                    if (exact === want.toLowerCase()) { target = opts[j]; break; }
                  }
                }
                if (!target) {
                  for (var k = 0; k < opts.length; k++) {
                    var loose = String(opts[k].text || '').trim().toLowerCase();
                    if (loose.indexOf(want.toLowerCase()) !== -1) { target = opts[k]; break; }
                  }
                }
                if (!target) return 'option-not-found';
                try { el.focus(); } catch (e) {}
                el.value = target.value;
                el.dispatchEvent(new Event('input', { bubbles: true }));
                el.dispatchEvent(new Event('change', { bubbles: true }));
                return 'ok';
              } catch (e) {
                return 'error ' + String(e).replace(/["\\\n\r]/g, ' ').slice(0, 120);
              }
            })()
        """.trimIndent()
    }

    /**
     * Sends a single key to whatever currently has focus. This is how the agent dismisses a modal
     * (`Escape`), moves between fields (`Tab`) or submits an input that lives outside a form
     * (`Enter`), none of which the click/type scripts can express.
     */
    fun pressKey(literal: String): String = """
        (function(){
          try {
            var key = $literal;
            var opts = { key: key, code: key, bubbles: true, cancelable: true };
            var codes = {
              Enter: 13, Escape: 27, Tab: 9, Backspace: 8, Space: 32,
              ArrowUp: 38, ArrowDown: 40, ArrowLeft: 37, ArrowRight: 39
            };
            var code = codes[key];
            if (code === undefined) return 'unsupported-key';
            try { opts.keyCode = code; opts.which = code; } catch (e) {}
            var el = document.activeElement || document.body || document.documentElement;
            if (!el) return 'unsupported-key';
            el.dispatchEvent(new KeyboardEvent('keydown', opts));
            el.dispatchEvent(new KeyboardEvent('keypress', opts));
            el.dispatchEvent(new KeyboardEvent('keyup', opts));
            return 'ok';
          } catch (e) {
            return 'error ' + String(e).replace(/["\\\n\r]/g, ' ').slice(0, 120);
          }
        })()
    """.trimIndent()

    /** Scrolls the window; `amountPx` is already clamped by the tool layer. */
    fun scroll(direction: String, amountPx: Int): String = when (direction.lowercase()) {
        "up" -> "window.scrollBy(0, -$amountPx); 'ok'"
        "top" -> "window.scrollTo(0, 0); 'ok'"
        "bottom" -> "window.scrollTo(0, document.body.scrollHeight); 'ok'"
        else -> "window.scrollBy(0, $amountPx); 'ok'"
    }
}
